# Generated by Django 5.2.3 on 2025-08-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price_per_night',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
